In [1]:
import json
import pandas as pd
import tweepy
import networkx as nx

In [2]:
with open("twitter_credentials.json", "r") as file:
    data = file.read()
    
credentials = json.loads(data)
client = tweepy.Client(bearer_token=credentials["BEARER_TOKEN"])

In [3]:
df = pd.read_csv('following_list_catcontentonly.csv')
G = nx.from_pandas_edgelist(df, 'source', 'target')

G.number_of_nodes()

295784

In [4]:
# finding most central nodes

num_nodes = 25

G_sorted = pd.DataFrame(sorted(G.degree, key=lambda x: x[1], reverse=True))
G_sorted.index.name = 'Rank'
G_sorted.columns = ['nconst','degree']
top_central = G_sorted.head(num_nodes)

In [5]:
pd.options.mode.chained_assignment = None  # default='warn', turns off warnings

top_central['username'] = top_central.apply(lambda row: client.get_user(id = int(row.nconst)).data.username, axis = 1)
top_central['url'] = top_central.apply(lambda row: "https://twitter.com/" + str(row.username), axis = 1)

def make_clickable(val):
    # target _blank to open new window
    return '<a target="_blank" href="{}">{}</a>'.format(val, val)

top_central.style.format({'url': make_clickable})

In [6]:
id = client.get_user(username='BenjaminNorton').data.id

G_sorted.loc[G_sorted['nconst'] == id]

           nconst  degree
Rank
622   852269288.0     722

In [7]:
starting_accts = ["BenjaminNorton",
                 "MaxBlumenthal",
                 "TheGrayZoneNews",
                 "AdamJohnsonNYC",
                 "CarlZha",
                 "CatContentOnly",
                 "SpiritofHo",
                 "agent_of_change",
                 "plbmagazine",
                 "AlanRMacLeod"]

for username in starting_accts:
    user_id = client.get_user(username=username).data
    print(username)
    if user_id:
        row = G_sorted.loc[G_sorted['nconst'] == user_id.id]
        print(row[['degree']])
        
    print(" ")

BenjaminNorton
      degree
Rank
622      722

MaxBlumenthal
      degree
Rank
853      160

TheGrayZoneNews
      degree
Rank
860      153

AdamJohnsonNYC
      degree
Rank
8       1165

CarlZha
      degree
Rank
524      962

CatContentOnly
      degree
Rank
143     1045

SpiritofHo
      degree
Rank
15      1144

agent_of_change
      degree
Rank
36      1111

plbmagazine
      degree
Rank
444     1000
905      118

AlanRMacLeod
      degree
Rank
52      1092